// Lista completa de países con traducciones
export const PAISES_ES = [
  { codigo: '', nombre: 'Seleccione un país' },
  { codigo: 'AF', nombre: 'Afganistán' },
  { codigo: 'AL', nombre: 'Albania' },
  { codigo: 'DE', nombre: 'Alemania' },
  { codigo: 'AD', nombre: 'Andorra' },
  { codigo: 'AO', nombre: 'Angola' },
  { codigo: 'AG', nombre: 'Antigua y Barbuda' },
  { codigo: 'SA', nombre: 'Arabia Saudita' },
  { codigo: 'DZ', nombre: 'Argelia' },
  { codigo: 'AR', nombre: 'Argentina' },
  { codigo: 'AM', nombre: 'Armenia' },
  { codigo: 'AU', nombre: 'Australia' },
  { codigo: 'AT', nombre: 'Austria' },
  { codigo: 'AZ', nombre: 'Azerbaiyán' },
  { codigo: 'BS', nombre: 'Bahamas' },
  { codigo: 'BD', nombre: 'Bangladés' },
  { codigo: 'BB', nombre: 'Barbados' },
  { codigo: 'BH', nombre: 'Baréin' },
  { codigo: 'BE', nombre: 'Bélgica' },
  { codigo: 'BZ', nombre: 'Belice' },
  { codigo: 'BJ', nombre: 'Benín' },
  { codigo: 'BY', nombre: 'Bielorrusia' },
  { codigo: 'BO', nombre: 'Bolivia' },
  { codigo: 'BA', nombre: 'Bosnia y Herzegovina' },
  { codigo: 'BW', nombre: 'Botsuana' },
  { codigo: 'BR', nombre: 'Brasil' },
  { codigo: 'BN', nombre: 'Brunéi' },
  { codigo: 'BG', nombre: 'Bulgaria' },
  { codigo: 'BF', nombre: 'Burkina Faso' },
  { codigo: 'BI', nombre: 'Burundi' },
  { codigo: 'BT', nombre: 'Bután' },
  { codigo: 'CV', nombre: 'Cabo Verde' },
  { codigo: 'KH', nombre: 'Camboya' },
  { codigo: 'CM', nombre: 'Camerún' },
  { codigo: 'CA', nombre: 'Canadá' },
  { codigo: 'QA', nombre: 'Catar' },
  { codigo: 'TD', nombre: 'Chad' },
  { codigo: 'CL', nombre: 'Chile' },
  { codigo: 'CN', nombre: 'China' },
  { codigo: 'CY', nombre: 'Chipre' },
  { codigo: 'CO', nombre: 'Colombia' },
  { codigo: 'KM', nombre: 'Comoras' },
  { codigo: 'CG', nombre: 'Congo' },
  { codigo: 'KP', nombre: 'Corea del Norte' },
  { codigo: 'KR', nombre: 'Corea del Sur' },
  { codigo: 'CR', nombre: 'Costa Rica' },
  { codigo: 'CI', nombre: 'Costa de Marfil' },
  { codigo: 'HR', nombre: 'Croacia' },
  { codigo: 'CU', nombre: 'Cuba' },
  { codigo: 'DK', nombre: 'Dinamarca' },
  { codigo: 'DM', nombre: 'Dominica' },
  { codigo: 'EC', nombre: 'Ecuador' },
  { codigo: 'EG', nombre: 'Egipto' },
  { codigo: 'SV', nombre: 'El Salvador' },
  { codigo: 'AE', nombre: 'Emiratos Árabes Unidos' },
  { codigo: 'ER', nombre: 'Eritrea' },
  { codigo: 'SK', nombre: 'Eslovaquia' },
  { codigo: 'SI', nombre: 'Eslovenia' },
  { codigo: 'ES', nombre: 'España' },
  { codigo: 'US', nombre: 'Estados Unidos' },
  { codigo: 'EE', nombre: 'Estonia' },
  { codigo: 'SZ', nombre: 'Esuatini' },
  { codigo: 'ET', nombre: 'Etiopía' },
  { codigo: 'PH', nombre: 'Filipinas' },
  { codigo: 'FI', nombre: 'Finlandia' },
  { codigo: 'FJ', nombre: 'Fiyi' },
  { codigo: 'FR', nombre: 'Francia' },
  { codigo: 'GA', nombre: 'Gabón' },
  { codigo: 'GM', nombre: 'Gambia' },
  { codigo: 'GE', nombre: 'Georgia' },
  { codigo: 'GH', nombre: 'Ghana' },
  { codigo: 'GR', nombre: 'Grecia' },
  { codigo: 'GD', nombre: 'Granada' },
  { codigo: 'GT', nombre: 'Guatemala' },
  { codigo: 'GN', nombre: 'Guinea' },
  { codigo: 'GQ', nombre: 'Guinea Ecuatorial' },
  { codigo: 'GW', nombre: 'Guinea-Bisáu' },
  { codigo: 'GY', nombre: 'Guyana' },
  { codigo: 'HT', nombre: 'Haití' },
  { codigo: 'HN', nombre: 'Honduras' },
  { codigo: 'HU', nombre: 'Hungría' },
  { codigo: 'IN', nombre: 'India' },
  { codigo: 'ID', nombre: 'Indonesia' },
  { codigo: 'IQ', nombre: 'Irak' },
  { codigo: 'IR', nombre: 'Irán' },
  { codigo: 'IE', nombre: 'Irlanda' },
  { codigo: 'IS', nombre: 'Islandia' },
  { codigo: 'IL', nombre: 'Israel' },
  { codigo: 'IT', nombre: 'Italia' },
  { codigo: 'JM', nombre: 'Jamaica' },
  { codigo: 'JP', nombre: 'Japón' },
  { codigo: 'JO', nombre: 'Jordania' },
  { codigo: 'KZ', nombre: 'Kazajistán' },
  { codigo: 'KE', nombre: 'Kenia' },
  { codigo: 'KG', nombre: 'Kirguistán' },
  { codigo: 'KI', nombre: 'Kiribati' },
  { codigo: 'KW', nombre: 'Kuwait' },
  { codigo: 'LA', nombre: 'Laos' },
  { codigo: 'LS', nombre: 'Lesoto' },
  { codigo: 'LV', nombre: 'Letonia' },
  { codigo: 'LB', nombre: 'Líbano' },
  { codigo: 'LR', nombre: 'Liberia' },
  { codigo: 'LY', nombre: 'Libia' },
  { codigo: 'LI', nombre: 'Liechtenstein' },
  { codigo: 'LT', nombre: 'Lituania' },
  { codigo: 'LU', nombre: 'Luxemburgo' },
  { codigo: 'MK', nombre: 'Macedonia del Norte' },
  { codigo: 'MG', nombre: 'Madagascar' },
  { codigo: 'MY', nombre: 'Malasia' },
  { codigo: 'MW', nombre: 'Malaui' },
  { codigo: 'MV', nombre: 'Maldivas' },
  { codigo: 'ML', nombre: 'Malí' },
  { codigo: 'MT', nombre: 'Malta' },
  { codigo: 'MA', nombre: 'Marruecos' },
  { codigo: 'MH', nombre: 'Islas Marshall' },
  { codigo: 'MU', nombre: 'Mauricio' },
  { codigo: 'MR', nombre: 'Mauritania' },
  { codigo: 'MX', nombre: 'México' },
  { codigo: 'FM', nombre: 'Micronesia' },
  { codigo: 'MD', nombre: 'Moldavia' },
  { codigo: 'MC', nombre: 'Mónaco' },
  { codigo: 'MN', nombre: 'Mongolia' },
  { codigo: 'ME', nombre: 'Montenegro' },
  { codigo: 'MZ', nombre: 'Mozambique' },
  { codigo: 'MM', nombre: 'Myanmar' },
  { codigo: 'NA', nombre: 'Namibia' },
  { codigo: 'NR', nombre: 'Nauru' },
  { codigo: 'NP', nombre: 'Nepal' },
  { codigo: 'NI', nombre: 'Nicaragua' },
  { codigo: 'NE', nombre: 'Níger' },
  { codigo: 'NG', nombre: 'Nigeria' },
  { codigo: 'NO', nombre: 'Noruega' },
  { codigo: 'NZ', nombre: 'Nueva Zelanda' },
  { codigo: 'OM', nombre: 'Omán' },
  { codigo: 'NL', nombre: 'Países Bajos' },
  { codigo: 'PK', nombre: 'Pakistán' },
  { codigo: 'PW', nombre: 'Palaos' },
  { codigo: 'PA', nombre: 'Panamá' },
  { codigo: 'PG', nombre: 'Papúa Nueva Guinea' },
  { codigo: 'PY', nombre: 'Paraguay' },
  { codigo: 'PE', nombre: 'Perú' },
  { codigo: 'PL', nombre: 'Polonia' },
  { codigo: 'PT', nombre: 'Portugal' },
  { codigo: 'GB', nombre: 'Reino Unido' },
  { codigo: 'CF', nombre: 'República Centroafricana' },
  { codigo: 'CZ', nombre: 'República Checa' },
  { codigo: 'CD', nombre: 'República Democrática del Congo' },
  { codigo: 'DO', nombre: 'República Dominicana' },
  { codigo: 'RW', nombre: 'Ruanda' },
  { codigo: 'RO', nombre: 'Rumania' },
  { codigo: 'RU', nombre: 'Rusia' },
  { codigo: 'WS', nombre: 'Samoa' },
  { codigo: 'KN', nombre: 'San Cristóbal y Nieves' },
  { codigo: 'SM', nombre: 'San Marino' },
  { codigo: 'VC', nombre: 'San Vicente y las Granadinas' },
  { codigo: 'LC', nombre: 'Santa Lucía' },
  { codigo: 'ST', nombre: 'Santo Tomé y Príncipe' },
  { codigo: 'SN', nombre: 'Senegal' },
  { codigo: 'RS', nombre: 'Serbia' },
  { codigo: 'SC', nombre: 'Seychelles' },
  { codigo: 'SL', nombre: 'Sierra Leona' },
  { codigo: 'SG', nombre: 'Singapur' },
  { codigo: 'SY', nombre: 'Siria' },
  { codigo: 'SO', nombre: 'Somalia' },
  { codigo: 'LK', nombre: 'Sri Lanka' },
  { codigo: 'ZA', nombre: 'Sudáfrica' },
  { codigo: 'SD', nombre: 'Sudán' },
  { codigo: 'SS', nombre: 'Sudán del Sur' },
  { codigo: 'SE', nombre: 'Suecia' },
  { codigo: 'CH', nombre: 'Suiza' },
  { codigo: 'SR', nombre: 'Surinam' },
  { codigo: 'TH', nombre: 'Tailandia' },
  { codigo: 'TZ', nombre: 'Tanzania' },
  { codigo: 'TJ', nombre: 'Tayikistán' },
  { codigo: 'TL', nombre: 'Timor Oriental' },
  { codigo: 'TG', nombre: 'Togo' },
  { codigo: 'TO', nombre: 'Tonga' },
  { codigo: 'TT', nombre: 'Trinidad y Tobago' },
  { codigo: 'TN', nombre: 'Túnez' },
  { codigo: 'TM', nombre: 'Turkmenistán' },
  { codigo: 'TR', nombre: 'Turquía' },
  { codigo: 'TV', nombre: 'Tuvalu' },
  { codigo: 'UA', nombre: 'Ucrania' },
  { codigo: 'UG', nombre: 'Uganda' },
  { codigo: 'UY', nombre: 'Uruguay' },
  { codigo: 'UZ', nombre: 'Uzbekistán' },
  { codigo: 'VU', nombre: 'Vanuatu' },
  { codigo: 'VA', nombre: 'Vaticano' },
  { codigo: 'VE', nombre: 'Venezuela' },
  { codigo: 'VN', nombre: 'Vietnam' },
  { codigo: 'YE', nombre: 'Yemen' },
  { codigo: 'DJ', nombre: 'Yibuti' },
  { codigo: 'ZM', nombre: 'Zambia' },
  { codigo: 'ZW', nombre: 'Zimbabue' },
];

export const PAISES_EN = [
  { codigo: '', nombre: 'Select a country' },
  { codigo: 'AF', nombre: 'Afghanistan' },
  { codigo: 'AL', nombre: 'Albania' },
  { codigo: 'DE', nombre: 'Germany' },
  { codigo: 'AD', nombre: 'Andorra' },
  { codigo: 'AO', nombre: 'Angola' },
  { codigo: 'AG', nombre: 'Antigua and Barbuda' },
  { codigo: 'SA', nombre: 'Saudi Arabia' },
  { codigo: 'DZ', nombre: 'Algeria' },
  { codigo: 'AR', nombre: 'Argentina' },
  { codigo: 'AM', nombre: 'Armenia' },
  { codigo: 'AU', nombre: 'Australia' },
  { codigo: 'AT', nombre: 'Austria' },
  { codigo: 'AZ', nombre: 'Azerbaijan' },
  { codigo: 'BS', nombre: 'Bahamas' },
  { codigo: 'BD', nombre: 'Bangladesh' },
  { codigo: 'BB', nombre: 'Barbados' },
  { codigo: 'BH', nombre: 'Bahrain' },
  { codigo: 'BE', nombre: 'Belgium' },
  { codigo: 'BZ', nombre: 'Belize' },
  { codigo: 'BJ', nombre: 'Benin' },
  { codigo: 'BY', nombre: 'Belarus' },
  { codigo: 'BO', nombre: 'Bolivia' },
  { codigo: 'BA', nombre: 'Bosnia and Herzegovina' },
  { codigo: 'BW', nombre: 'Botswana' },
  { codigo: 'BR', nombre: 'Brazil' },
  { codigo: 'BN', nombre: 'Brunei' },
  { codigo: 'BG', nombre: 'Bulgaria' },
  { codigo: 'BF', nombre: 'Burkina Faso' },
  { codigo: 'BI', nombre: 'Burundi' },
  { codigo: 'BT', nombre: 'Bhutan' },
  { codigo: 'CV', nombre: 'Cape Verde' },
  { codigo: 'KH', nombre: 'Cambodia' },
  { codigo: 'CM', nombre: 'Cameroon' },
  { codigo: 'CA', nombre: 'Canada' },
  { codigo: 'QA', nombre: 'Qatar' },
  { codigo: 'TD', nombre: 'Chad' },
  { codigo: 'CL', nombre: 'Chile' },
  { codigo: 'CN', nombre: 'China' },
  { codigo: 'CY', nombre: 'Cyprus' },
  { codigo: 'CO', nombre: 'Colombia' },
  { codigo: 'KM', nombre: 'Comoros' },
  { codigo: 'CG', nombre: 'Congo' },
  { codigo: 'KP', nombre: 'North Korea' },
  { codigo: 'KR', nombre: 'South Korea' },
  { codigo: 'CR', nombre: 'Costa Rica' },
  { codigo: 'CI', nombre: 'Ivory Coast' },
  { codigo: 'HR', nombre: 'Croatia' },
  { codigo: 'CU', nombre: 'Cuba' },
  { codigo: 'DK', nombre: 'Denmark' },
  { codigo: 'DM', nombre: 'Dominica' },
  { codigo: 'EC', nombre: 'Ecuador' },
  { codigo: 'EG', nombre: 'Egypt' },
  { codigo: 'SV', nombre: 'El Salvador' },
  { codigo: 'AE', nombre: 'United Arab Emirates' },
  { codigo: 'ER', nombre: 'Eritrea' },
  { codigo: 'SK', nombre: 'Slovakia' },
  { codigo: 'SI', nombre: 'Slovenia' },
  { codigo: 'ES', nombre: 'Spain' },
  { codigo: 'US', nombre: 'United States' },
  { codigo: 'EE', nombre: 'Estonia' },
  { codigo: 'SZ', nombre: 'Eswatini' },
  { codigo: 'ET', nombre: 'Ethiopia' },
  { codigo: 'PH', nombre: 'Philippines' },
  { codigo: 'FI', nombre: 'Finland' },
  { codigo: 'FJ', nombre: 'Fiji' },
  { codigo: 'FR', nombre: 'France' },
  { codigo: 'GA', nombre: 'Gabon' },
  { codigo: 'GM', nombre: 'Gambia' },
  { codigo: 'GE', nombre: 'Georgia' },
  { codigo: 'GH', nombre: 'Ghana' },
  { codigo: 'GR', nombre: 'Greece' },
  { codigo: 'GD', nombre: 'Grenada' },
  { codigo: 'GT', nombre: 'Guatemala' },
  { codigo: 'GN', nombre: 'Guinea' },
  { codigo: 'GQ', nombre: 'Equatorial Guinea' },
  { codigo: 'GW', nombre: 'Guinea-Bissau' },
  { codigo: 'GY', nombre: 'Guyana' },
  { codigo: 'HT', nombre: 'Haiti' },
  { codigo: 'HN', nombre: 'Honduras' },
  { codigo: 'HU', nombre: 'Hungary' },
  { codigo: 'IN', nombre: 'India' },
  { codigo: 'ID', nombre: 'Indonesia' },
  { codigo: 'IQ', nombre: 'Iraq' },
  { codigo: 'IR', nombre: 'Iran' },
  { codigo: 'IE', nombre: 'Ireland' },
  { codigo: 'IS', nombre: 'Iceland' },
  { codigo: 'IL', nombre: 'Israel' },
  { codigo: 'IT', nombre: 'Italy' },
  { codigo: 'JM', nombre: 'Jamaica' },
  { codigo: 'JP', nombre: 'Japan' },
  { codigo: 'JO', nombre: 'Jordan' },
  { codigo: 'KZ', nombre: 'Kazakhstan' },
  { codigo: 'KE', nombre: 'Kenya' },
  { codigo: 'KG', nombre: 'Kyrgyzstan' },
  { codigo: 'KI', nombre: 'Kiribati' },
  { codigo: 'KW', nombre: 'Kuwait' },
  { codigo: 'LA', nombre: 'Laos' },
  { codigo: 'LS', nombre: 'Lesotho' },
  { codigo: 'LV', nombre: 'Latvia' },
  { codigo: 'LB', nombre: 'Lebanon' },
  { codigo: 'LR', nombre: 'Liberia' },
  { codigo: 'LY', nombre: 'Libya' },
  { codigo: 'LI', nombre: 'Liechtenstein' },
  { codigo: 'LT', nombre: 'Lithuania' },
  { codigo: 'LU', nombre: 'Luxembourg' },
  { codigo: 'MK', nombre: 'North Macedonia' },
  { codigo: 'MG', nombre: 'Madagascar' },
  { codigo: 'MY', nombre: 'Malaysia' },
  { codigo: 'MW', nombre: 'Malawi' },
  { codigo: 'MV', nombre: 'Maldives' },
  { codigo: 'ML', nombre: 'Mali' },
  { codigo: 'MT', nombre: 'Malta' },
  { codigo: 'MA', nombre: 'Morocco' },
  { codigo: 'MH', nombre: 'Marshall Islands' },
  { codigo: 'MU', nombre: 'Mauritius' },
  { codigo: 'MR', nombre: 'Mauritania' },
  { codigo: 'MX', nombre: 'Mexico' },
  { codigo: 'FM', nombre: 'Micronesia' },
  { codigo: 'MD', nombre: 'Moldova' },
  { codigo: 'MC', nombre: 'Monaco' },
  { codigo: 'MN', nombre: 'Mongolia' },
  { codigo: 'ME', nombre: 'Montenegro' },
  { codigo: 'MZ', nombre: 'Mozambique' },
  { codigo: 'MM', nombre: 'Myanmar' },
  { codigo: 'NA', nombre: 'Namibia' },
  { codigo: 'NR', nombre: 'Nauru' },
  { codigo: 'NP', nombre: 'Nepal' },
  { codigo: 'NI', nombre: 'Nicaragua' },
  { codigo: 'NE', nombre: 'Niger' },
  { codigo: 'NG', nombre: 'Nigeria' },
  { codigo: 'NO', nombre: 'Norway' },
  { codigo: 'NZ', nombre: 'New Zealand' },
  { codigo: 'OM', nombre: 'Oman' },
  { codigo: 'NL', nombre: 'Netherlands' },
  { codigo: 'PK', nombre: 'Pakistan' },
  { codigo: 'PW', nombre: 'Palau' },
  { codigo: 'PA', nombre: 'Panama' },
  { codigo: 'PG', nombre: 'Papua New Guinea' },
  { codigo: 'PY', nombre: 'Paraguay' },
  { codigo: 'PE', nombre: 'Peru' },
  { codigo: 'PL', nombre: 'Poland' },
  { codigo: 'PT', nombre: 'Portugal' },
  { codigo: 'GB', nombre: 'United Kingdom' },
  { codigo: 'CF', nombre: 'Central African Republic' },
  { codigo: 'CZ', nombre: 'Czech Republic' },
  { codigo: 'CD', nombre: 'Democratic Republic of the Congo' },
  { codigo: 'DO', nombre: 'Dominican Republic' },
  { codigo: 'RW', nombre: 'Rwanda' },
  { codigo: 'RO', nombre: 'Romania' },
  { codigo: 'RU', nombre: 'Russia' },
  { codigo: 'WS', nombre: 'Samoa' },
  { codigo: 'KN', nombre: 'Saint Kitts and Nevis' },
  { codigo: 'SM', nombre: 'San Marino' },
  { codigo: 'VC', nombre: 'Saint Vincent and the Grenadines' },
  { codigo: 'LC', nombre: 'Saint Lucia' },
  { codigo: 'ST', nombre: 'Sao Tome and Principe' },
  { codigo: 'SN', nombre: 'Senegal' },
  { codigo: 'RS', nombre: 'Serbia' },
  { codigo: 'SC', nombre: 'Seychelles' },
  { codigo: 'SL', nombre: 'Sierra Leone' },
  { codigo: 'SG', nombre: 'Singapore' },
  { codigo: 'SY', nombre: 'Syria' },
  { codigo: 'SO', nombre: 'Somalia' },
  { codigo: 'LK', nombre: 'Sri Lanka' },
  { codigo: 'ZA', nombre: 'South Africa' },
  { codigo: 'SD', nombre: 'Sudan' },
  { codigo: 'SS', nombre: 'South Sudan' },
  { codigo: 'SE', nombre: 'Sweden' },
  { codigo: 'CH', nombre: 'Switzerland' },
  { codigo: 'SR', nombre: 'Suriname' },
  { codigo: 'TH', nombre: 'Thailand' },
  { codigo: 'TZ', nombre: 'Tanzania' },
  { codigo: 'TJ', nombre: 'Tajikistan' },
  { codigo: 'TL', nombre: 'East Timor' },
  { codigo: 'TG', nombre: 'Togo' },
  { codigo: 'TO', nombre: 'Tonga' },
  { codigo: 'TT', nombre: 'Trinidad and Tobago' },
  { codigo: 'TN', nombre: 'Tunisia' },
  { codigo: 'TM', nombre: 'Turkmenistan' },
  { codigo: 'TR', nombre: 'Turkey' },
  { codigo: 'TV', nombre: 'Tuvalu' },
  { codigo: 'UA', nombre: 'Ukraine' },
  { codigo: 'UG', nombre: 'Uganda' },
  { codigo: 'UY', nombre: 'Uruguay' },
  { codigo: 'UZ', nombre: 'Uzbekistan' },
  { codigo: 'VU', nombre: 'Vanuatu' },
  { codigo: 'VA', nombre: 'Vatican' },
  { codigo: 'VE', nombre: 'Venezuela' },
  { codigo: 'VN', nombre: 'Vietnam' },
  { codigo: 'YE', nombre: 'Yemen' },
  { codigo: 'DJ', nombre: 'Djibouti' },
  { codigo: 'ZM', nombre: 'Zambia' },
  { codigo: 'ZW', nombre: 'Zimbabwe' },
];

// Función helper para obtener la lista de países según el idioma
export const obtenerPaises = (idioma = 'es') => {
  return idioma === 'en' ? PAISES_EN : PAISES_ES;
};

// Mantener exportación legacy para compatibilidad
export const PAISES = PAISES_ES;
